"""oi]

Revision ID: 95881a15582a
Revises: 
Create Date: 2024-09-11 19:45:59.286834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95881a15582a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estagio_programa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estagio_atual', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('proximo_estagio', sa.String(length=100), nullable=False),
    sa.Column('taxa_atual', sa.Float(), nullable=False),
    sa.Column('objetivo_proximo', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grande_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grande_problema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habilidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hipotese',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('habilidades', sa.Text(), nullable=True),
    sa.Column('nivel', sa.String(length=50), nullable=False),
    sa.Column('formacao', sa.String(length=100), nullable=True),
    sa.Column('instituicao', sa.String(length=100), nullable=True),
    sa.Column('vinculo', sa.String(length=100), nullable=True),
    sa.Column('especialidades', sa.Text(), nullable=True),
    sa.Column('historico', sa.Text(), nullable=True),
    sa.Column('moedas_trabalho', sa.Integer(), nullable=True),
    sa.Column('pontos', sa.Integer(), nullable=True),
    sa.Column('badges', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('atividade_equipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_atividade', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipe_membros',
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipe.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('equipe_id', 'usuario_id')
    )
    op.create_table('forum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('criador_id', sa.Integer(), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criador_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remetente_id', sa.Integer(), nullable=True),
    sa.Column('destinatario_id', sa.Integer(), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destinatario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['remetente_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('equipe', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('prazo_revisao', sa.String(length=50), nullable=True),
    sa.Column('recursos_aprovados', sa.Integer(), nullable=True),
    sa.Column('nivel_atual', sa.Integer(), nullable=True),
    sa.Column('recursos_necessarios', sa.Integer(), nullable=False),
    sa.Column('recursos_manutencao', sa.Integer(), nullable=True),
    sa.Column('sugestao_problema', sa.String(length=255), nullable=False),
    sa.Column('tarefas_completadas', sa.Integer(), nullable=True),
    sa.Column('contribuicao_financeira', sa.Float(), nullable=True),
    sa.Column('contribuicao_trabalho', sa.Float(), nullable=True),
    sa.Column('grande_area_id', sa.Integer(), nullable=True),
    sa.Column('hipotese_id', sa.Integer(), nullable=True),
    sa.Column('questao_id', sa.Integer(), nullable=True),
    sa.Column('grande_problema_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grande_area_id'], ['grande_area.id'], ),
    sa.ForeignKeyConstraint(['grande_problema_id'], ['grande_problema.id'], ),
    sa.ForeignKeyConstraint(['hipotese_id'], ['hipotese.id'], ),
    sa.ForeignKeyConstraint(['questao_id'], ['questao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliacao_equipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('avaliador', sa.String(length=100), nullable=False),
    sa.Column('data_avaliacao', sa.DateTime(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipe.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fase_projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('percentual', sa.Float(), nullable=False),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('auditor', sa.String(length=100), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('data_avaliacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financiamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('valor_financiado', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarefa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('complexidade', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_transacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_tarefas',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tarefa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tarefa_id'], ['tarefa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'tarefa_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios_tarefas')
    op.drop_table('transacao')
    op.drop_table('tarefa')
    op.drop_table('financiamento')
    op.drop_table('feedback')
    op.drop_table('fase_projeto')
    op.drop_table('avaliacao_equipe')
    op.drop_table('projeto')
    op.drop_table('mensagem')
    op.drop_table('forum')
    op.drop_table('equipe_membros')
    op.drop_table('atividade_equipe')
    op.drop_table('usuario')
    op.drop_table('questao')
    op.drop_table('hipotese')
    op.drop_table('habilidade')
    op.drop_table('grande_problema')
    op.drop_table('grande_area')
    op.drop_table('estagio_programa')
    op.drop_table('equipe')
    # ### end Alembic commands ###
