"""Iniciando do zero

Revision ID: e4142e2bed4d
Revises: 
Create Date: 2024-09-05 01:05:22.883748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4142e2bed4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habilidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('equipe', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('prazo_revisao', sa.String(length=50), nullable=True),
    sa.Column('recursos_aprovados', sa.Integer(), nullable=True),
    sa.Column('nivel_atual', sa.Integer(), nullable=True),
    sa.Column('recursos_necessarios', sa.Integer(), nullable=False),
    sa.Column('recursos_manutencao', sa.Integer(), nullable=True),
    sa.Column('contribuicao_financeira', sa.Float(), nullable=True),
    sa.Column('contribuicao_trabalho', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarefa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('complexidade', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('habilidades', sa.Text(), nullable=True),
    sa.Column('nivel', sa.String(length=50), nullable=False),
    sa.Column('historico', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('atividade_equipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_atividade', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliacao_equipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('avaliador', sa.String(length=100), nullable=False),
    sa.Column('data_avaliacao', sa.DateTime(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipe.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipe_membros',
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipe.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('equipe_id', 'usuario_id')
    )
    op.create_table('fase_projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('percentual', sa.Float(), nullable=False),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fase_projeto')
    op.drop_table('equipe_membros')
    op.drop_table('avaliacao_equipe')
    op.drop_table('atividade_equipe')
    op.drop_table('usuario')
    op.drop_table('tarefa')
    op.drop_table('projeto')
    op.drop_table('habilidade')
    op.drop_table('equipe')
    # ### end Alembic commands ###
